id: I4A406124
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-02-02T10:10:27+00:00'
last_modified: '2022-06-10T10:27:20.643819+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14303
  title: གསུང་འབུམ། ཆོས་ཀྱི་བློ་གྲོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EFE0:
      image_group_id: I1KG15193
      title: ''
      total_pages: 362
      order: 1
      base_file: EFE0.txt
    '1266':
      image_group_id: I1KG15194
      title: ''
      total_pages: 328
      order: 2
      base_file: 1266.txt
    '7461':
      image_group_id: I1KG15195
      title: ''
      total_pages: 328
      order: 3
      base_file: 7461.txt
    '5599':
      image_group_id: I1KG15196
      title: ''
      total_pages: 336
      order: 4
      base_file: 5599.txt
    5F3C:
      image_group_id: I1KG15197
      title: ''
      total_pages: 360
      order: 5
      base_file: 5F3C.txt
    D59F:
      image_group_id: I1KG15198
      title: ''
      total_pages: 305
      order: 6
      base_file: D59F.txt
    DAA8:
      image_group_id: I1KG15199
      title: ''
      total_pages: 317
      order: 7
      base_file: DAA8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
